language: go

go:
 - 1.13.x

services:
 - docker

env:
  matrix:
    - DOCKERFILE=.deploy/itu-minitwit-api/Dockerfile
      BUILD_NAME=minitwit-api:latest
    - DOCKERFILE=.deploy/itu-minitwit-go/Dockerfile
      BUILD_NAME=minitwit:latest

before_install:
 - docker compose up

script:
 - docker build -t ${BUILD_NAME} . -f ${DOCKERFILE}
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push ${BUILD_NAME}
