language: go

go:
 - 1.13.x

services:
 - docker

env:
  matrix:
    - DOCKERFILE=.deploy/itu-minitwit-api/Dockerfile
      BUILD_NAME=minitwit-api:latest
    - DOCKERFILE=.deploy/itu-minitwit-go/Dockerfile
      BUILD_NAME=minitwit:latest

stages:
  - before_build
  - docker_build
  - deploy

jobs:
  include:
    - stage: before_build
      name: "preparation step"
      script:
       - echo "test"
       - openssl aes-256-cbc -K $encrypted_56635d5d55b3_key -iv $encrypted_56635d5d55b3_iv -in do_ssh_key.enc -out /tmp/git_deploy_key -d
       - chmod 600 /tmp/git_deploy_key
       - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
       - eval "$(ssh-agent -s)"
       - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
       - docker --version
      
    - stage: docker_build
      name: "build and push docker"      
      script:
       - docker build -t ${BUILD_NAME} . -f ${DOCKERFILE}
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       - docker tag ${BUILD_NAME} jonaswg/${BUILD_NAME}
       - docker push jonaswg/${BUILD_NAME}

    - stage: deploy
      name: "deploy new version"
      install: skip
      script:
       - ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER}
       - source /root/.bash_profile
       - cd /vagrant
       - docker-compose pull
       - docker-compose up -d
