language: go

go:
 - 1.13.x

services:
 - docker

addons:
  sonarcloud:
    organization: "itu-devops-team" # the key of the org you chose at step #3
    token:
      secure: "n2ptbc0dMv6hlApOLTnGaYapE3Wu0IiYbGbzgZwZoB/Bdt7N3cVjayVwlrbzF38uUzTrFmYXBNnQ/6mZ+MiLIXnnCSi2vwR27/45bhcczX4EqNkf++YE52Ik7JkGSrTcqqfR/TWHZqTYlbkVkS0rorAPDFMhZPtGIRU8KbRzJGIG8U64oIWzaZLUu+MdFlzEqfQkGy1tbF7astin0d/30EWBu+KScNxbGTl9m2Oe3IFKmt2dm7IuJE8CEN7oFm2Vu4K+0Ob5dQyhuXNUwZnNLCHi7UhX0FY2HKviYFtkG251vr7iJJRmTiJiB4qs8U7uY6cpjhVbw7aI6zFjUZMqS621jCWHpK2L9fnqz9r8BPjeddHQ9+3wFwmhCphoWr2ub/pkValqhuX9MC3uuWyQEZ7Vd6Vv93pgNqBzCafNvbrQ9SPJrzherABSsTxypJQSbgcREUWe5ewidv/9BUflvO4cv/Bh1Z2d9/tnn+P3UDINI3H7FyxItxEqkgNail1geBNc79YBuYeW2di2rVQZdDb/zWNkmOD3IlHrbxHeCINSSndqVlUFWTXES/H142gWZmAZ8UpzCN2IyZFRN8jwKq/Tmq6nD8d3Y3fPpYEWPw5nmu6y3TK5pGzNAD75+mDKGaWzlpAhTZa6ewQxm+aRoSPSkQwl2U7XqYtn76MBaTM=" # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner

env:
  matrix:
    - DOCKERFILE=.deploy/itu-minitwit-api/Dockerfile
      BUILD_NAME=minitwit-api:latest
    - DOCKERFILE=.deploy/itu-minitwit-go/Dockerfile
      BUILD_NAME=minitwit:latest

stages:
  - before_build
  - docker_build
  - deploy

jobs:
  include:
    - stage: before_build
      name: "preparation step"
      script:
       - openssl aes-256-cbc -K $encrypted_56635d5d55b3_key -iv $encrypted_56635d5d55b3_iv -in do_ssh_key.enc -out /tmp/git_deploy_key -d
       - chmod 600 /tmp/git_deploy_key
       - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
       - eval "$(ssh-agent -s)"
       - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
       - docker --version
      
    - stage: docker_build
      name: "build and push docker"      
      script:
       - docker build -t ${BUILD_NAME} . -f ${DOCKERFILE}
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       - docker tag ${BUILD_NAME} jonaswg/${BUILD_NAME}
       - docker push jonaswg/${BUILD_NAME}

    - stage: deploy
      name: "deploy new version"
      install: skip
      script:
       - ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER}
       - source /root/.bash_profile
       - cd /vagrant
       - docker-compose pull
       - docker-compose up -d
