language: go

go:
 - 1.13.x

services:
 - docker

env:
  matrix:
    - DOCKERFILE=minitwit-api
      BUILD_NAME=minitwit-api:latest
    - DOCKERFILE=minitwit
      BUILD_NAME=minitwit:latest


before_install:
 - docker compose up

script:
 - docker compose up ${DOCKERFILE}
 - docker push ${BUILD_NAME}
