language: go

go:
 - 1.13.x

services:
 - docker

env:
  matrix:
    - DOCKERFILE=.deploy/itu-minitwit-api/Dockerfile
      BUILD_NAME=minitwit-api:latest
    - DOCKERFILE=.deploy/itu-minitwit-go/Dockerfile
      BUILD_NAME=minitwit:latest

stages:
  - docker_build
  - deploy

jobs:
  include:
    - stage: docker_build
      name: "build and push docker"      
      script:
       - docker build -t ${BUILD_NAME} . -f ${DOCKERFILE}
       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       - docker tag ${BUILD_NAME} jonaswg/${BUILD_NAME}
       - docker push jonaswg/${BUILD_NAME}

    - stage: deploy
      name: "deploy new version"
      install: skip
      script:
       - ssh -o "StrictHostKeyChecking no" ${MT_USER}@{MT_SERVER}
       - source /root/.bash_profile
       - cd /vagrant
       - docker-compose pull
       - docker-compose up -d
