language: go

go:
 - 1.13.x

services:
 - docker

env:
  matrix:
    - DOCKERFILE=.deploy/itu-minitwit-api/Dockerfile
      BUILD_NAME=minitwit-api:latest
    - DOCKERFILE=.deploy/itu-minitwit-go/Dockerfile
      BUILD_NAME=minitwit:latest


before_install:
 - docker compose up

script:
 - docker compose up ${DOCKERFILE}
 - docker push ${BUILD_NAME}
