version: "3"

services:
  minitwit:
    image: minitwit:latest
    build:
      context: .
      dockerfile: .deploy/itu-minitwit-go/Dockerfile
    restart: on-failure
    ports:
      - 8080:8080

  minitwit-api:
    image: minitwit-api:latest
    build:
      context: .
      dockerfile: .deploy/itu-minitwit-api/Dockerfile
    restart: on-failure
    ports:
      - 8081:8080
