version: "3"

services:
  minitwit:
    image: minitwit:latest
    build:
      context: .
      dockerfile: .deploy/itu-minitwit-go/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: database
    restart: on-failure
    depends_on: 
      - database
    ports:
      - 8080:8080

  minitwit-api:
    image: minitwit-api:latest
    build:
      context: .
      dockerfile: .deploy/itu-minitwit-api/Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: database
    restart: on-failure
    depends_on: 
      - database
    ports:
      - 8081:8080

  database:
    image: 'postgres'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-root}
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'psql postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@localhost:5432/$${POSTGRES_DB} || exit 1',
        ]

volumes:
  database-data:
