version: "3"

services:
  minitwit:
    image: minitwit:latest
    build:
      context: .
      dockerfile: .deploy/itu-minitwit-go/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    restart: on-failure
    ports:
      - 8080:8080

  minitwit-api:
    image: minitwit-api:latest
    build:
      context: .
      dockerfile: .deploy/itu-minitwit-api/Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    restart: on-failure
    ports:
      - 8081:8080