name: ci formatting

on:
  push:
    branches: 
      - development
  pull_request:
    branches:
      - development

jobs:
  format-minitwit:
    name: check formatting for minitwit
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go to minitwit dir
        run: cd itu-minitwit-go
      - name: run go fmt 
        run: go fmt
  
  format-minitwit-api:
    name: check formatting for minitwit-api
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go to minitwit-api dir
        run: cd itu-minitwit-api
      - name: run go fmt 
        run: go fmt
