name: ci formatting

on:
  push:
    branches: 
      - development
  pull_request:
    branches:
      - development

jobs:
  format-minitwit:
    name: check formatting for minitwit
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check minitwit code formatting
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-path: './itu-minitwit-go'
  
  format-minitwit-api:
    name: check formatting for minitwit-api
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check minitwit-api code formatting
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-path: './itu-minitwit-api'

