name: test documentation workflow

on: 
  push:
   branches:
     - test/*

jobs:
  generate-report:
    name: generate report.pdf based on the markdown docs
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get working directory
        run: echo "WORKING_DIR=$(pwd)" >> $GITHUB_ENV
      - name: publish markdown as pdf
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'report/docs/front/front-page.md report/docs/*'
      - name: upload document
        uses: actions/upload-artifact@v2
        id: upload-document
        with:
          name: report.pdf
          path: ${{ steps.publish-document.outputs.pdf }}
      - name: download document on runner
        uses: actions/download-artifact@v2
        with:
          name: report.pdf
          path: ~/downloads
      - name: rename document.pdf to report.pdf
        run: mv ~/downloads/document.pdf ~/downloads/report.pdf
      - name: copy report.pdf to report dir
        run: cp ~/downloads/report.pdf $WORKING_DIR/report/build
      - name: commit and push report.pdf
        run: |
          git add report/build
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@noreply.github.com'
          git commit -m 'chore: update report.pdf'
          git push
