name: test documentation workflow

on: 
  push:
   branches:
     - test/*

jobs:
  generate-report:
    name: generate report.pdf based on the markdown docs
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
     
      - name: print working dir
        run: pwd

      - name: list files in working dir
        run: ls -la $(pwd) 

      - name: check dir
        run: ls -la report/build
      - uses: mkrakowitzer/actions-makepdfs@master
        with:
          markdown_dir: report/docs
          output_dir: report/build
      - name: check dir
        run: ls -la report/build

      - name: commit and push report.pdf
        run: |
          git add report/build
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@noreply.github.com'
          git commit -m 'chore: update report.pdf'
          git push


      # - name: publish markdown as pdf
      #   uses: shrink/actions-document-publish@v1
      #   id: publish-document
      #   with:
      #     sources: 'report/docs/front/front-page.md report/docs/*'
      # - name: upload document
      #   uses: actions/upload-artifact@v2
      #   id: upload-document
      #   with:
      #     name: report.pdf
      #     path: ${{ steps.publish-document.outputs.pdf }}
      # - name: download document on runner
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: report.pdf
      #     path: ~/downloads/report.pdf
      # - name: check dir
      #   run: ls -la ~/downloads
      # - name: commit and push report.pdf
      #   uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-directory: ~/downloads
      #     destination-github-username: ITU-DevOps-Team
      #     destination-repository-name: ITU-DevOps
      #     user-email: actions@github.com
      #     target-branch: development

