name: test documentation workflow

on: 
  push:
   branches:
     - test/*

jobs:
  generate-report:
    name: generate report.pdf based on the markdown docs
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: publish markdown as pdf
        uses: shrink/actions-document-publish@v1
        id: publish-document
        with:
          sources: 'report/docs/front/front-page.md report/docs/*'

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: report.pdf
          destination_repo: ITU-DevOps-Team/ITU-DevOps
          destination_folder: report/build
          user_email: 'actions@github.com'
          user_name: 'github-actions'
          commit_message: 'Update report.pdf'


      # - name: upload document
      #   uses: actions/upload-artifact@v2
      #   id: upload-document
      #   with:
      #     name: report.pdf
      #     path: ${{ steps.publish-document.outputs.pdf }}
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: report.pdf
      #     path: report/build/